### ISSUE TITLE
TarkovTracker Integration

### ISSUE THREAD

**Issue by XenSide** [sammereye/TarkovHandbook#1]
By integrating TarkovTracker's API you would be able to know (and potentially add/remove) how many items are still needed for quests/hideout instead of showing the general total.

Also, you would be able to show crafts that you are actually able to do in the hideout page since you can track station levels aswell.

**Comment by woodypride94** [comment]
Agreed, this would be a nice addition.

**Comment by sammereye** [comment]
Implemented as a standalone feature, not utilizing TarkovTracker API
