### ISSUE TITLE
Tarkov Tools Shut down

### ISSUE THREAD

**Issue by Matthew-Rader** [sammereye/TarkovHandbook#12]
Tarkov Tools has been shut down resulting in the Items section of this app no longer working and throwing errors. 

Hopefully, this is just temporary, but maybe a new API should be used (if possible) or the Items section disabled to prevent the errors from getting thrown

**Comment by sammereye** [comment]
Hey, this project has been temporarily been put on hold and it especially doesn't help that Tarkov Tools is gone now as well.

**Comment by justforgithubandyou** [comment]
Many other places have gone on to use tarkov.dev I believe for their needs. You could get into contact with the people of RatScanner to have some help with using that?

**Comment by Matthew-Rader** [comment]
@sammereye would you be open to getting some dev assistance on this tool? This tool is super useful and if you need help I'd love to lend a hand.
