### ISSUE TITLE
TypeError: results.slice is not a function

### ISSUE THREAD

**Issue by justforgithubandyou** [sammereye/TarkovHandbook#13]
Keep getting this every time I even try to use the app now. Back to RatScanner i go :(

![image](https://user-images.githubusercontent.com/103540465/163066522-97633d55-7810-4d22-8cca-49522d2d6114.png)

Keep getting this every time I even try to use the app now

**Comment by Matthew-Rader** [comment]
It's related to this https://github.com/sammereye/TarkovHandbook/issues/12
