### ISSUE TITLE
Quests Photo Suggestion

### ISSUE THREAD

**Issue by woodypride94** [sammereye/TarkovHandbook#2]
Clicking on a photo under a quest guide should expand it to the size of the handbook overlay.

**Comment by sammereye** [comment]
That's a really good idea, I'll add it in the following update.

**Comment by sammereye** [comment]
@woodypride94 Implemented, will close once I push out the update
![preview2](https://user-images.githubusercontent.com/27503957/149990998-182bcf36-ae1c-4685-9a6a-866cc0bde0df.png)

**Comment by woodypride94** [comment]
Holy cow that was fast! You're the boss!

**Comment by sammereye** [comment]
Implemented in v1.0.1
