### ISSUE TITLE
Map section suggestion

### ISSUE THREAD

**Issue by Franmb93** [sammereye/TarkovHandbook#3]
First of all, amazing tool and job, thank you.

It would be fine if you can add one more tab with maps, so you can check the exits and loots throught it.

**Comment by sammereye** [comment]
Already working on it!
![preview](https://user-images.githubusercontent.com/27503957/149990503-c1249ab6-bbb6-4aa1-b182-8435088c2ed4.png)

**Comment by sammereye** [comment]
Implemented in v1.0.1
