### ISSUE TITLE
JS error occurred

### ISSUE THREAD

**Issue by mlueckl** [sammereye/TarkovHandbook#9]
- Error occurred while having the Game open and searching for the Quest "Easy Job - Part 1" by Prapor. 
- Handbook remained open but no longer returned the Quest when searched for

![tarkovhandbook-javascript-error](https://user-images.githubusercontent.com/11505613/152676468-7c0368da-0855-4c20-8b41-8c9169c51249.PNG)

**Comment by sammereye** [comment]
Thanks for providing me with the screenshot. I will look into this and let you know when its fixed.
